name: MSiege
version: ${project.version}
main: red.man10.msiege.MSiege
authors: [Mr_IK]
description: Man10 Siege Plugin
commands:
  msi:
    description: MSiege
    usage: /<command>
    default: op
  siege:
    description: MSiege
    usage: /<command>
    default: op
  tc:
    description: MSiege
    usage: /<command>
    default: op